### PR TITLE
New article about the plugin registry

### PR DESCRIPTION
**Pull request by takezoe**

### CODE REVIEW

**Comment by takezoe** [comment]
@aadrian Thanks for fixes!

**Comment by McFoggy** [comment]
@takezoe great to see this happening but I guess that if it is a need to update/rebuild/publish the plugins each time gitbucket is released (as far as I understood the publication) then it will be a pain for plugin maintainers and will for sure stop external plugin contributions.
You are in very good position to understand how much it already costs to OSS maintainers to maintain a project ; if additionally you enforce them to follow a one month delivery they'll stop supporting gitbucket.

**Comment by takezoe** [comment]
@McFoggy Oh no! Plugins are built and published automatically on the registry when new tags are added to either GitBucket or plugins if there aren't necessity of modifying source code. Plugin developers don't need to do it by hand. If there are necessity to modifying source code, it's notified to developers in daily check (but notification hasn't been implemented yet). 

Should I improve the article?

**Comment by McFoggy** [comment]
ha ok it was not clear to my eyes that you were recompiling/rebuilding the plugins from source when I first read the article.

**Comment by takezoe** [comment]
I'll try to update the article to explain them more cleary.

**Comment by McFoggy** [comment]
+1

**Pull request merged**
