### PR TITLE
Update 'recruit' page data and link it from the menu.

### PR DESCRIPTION
**Pull request by aadrian**

### CODE REVIEW

**Comment by takezoe** [comment]
@aadrian Thanks for update. We have to replace screenshots before restore a link from the top page because current screenshots were taken when GitBucket had similar design to GitHub.

**Comment by aadrian** [comment]
>  We have to replace screenshots before restore a link from the top page because current screenshots were taken when GitBucket had similar design to GitHub.

OK, I see. 

I'll try to update the screens later this evening (UTC+2), but I don't know how was this one:
https://github.com/gitbucket/gitbucket-news/blob/gh-pages/recruit/img/eyecatch-laptop.png
made? (since it's not just a screenshot)

**Comment by takezoe** [comment]
It's a mystery. I will ask author who is my colleague how to make it.

**Comment by takezoe** [comment]
@aadrian We got a sketch file to create that image in https://github.com/gitbucket/gitbucket-news/pull/27 from @haginot. But we need [Sketch](https://www.sketchapp.com/) to edit that file. If you don't have it, I will fix that sometime.

**Comment by aadrian** [comment]
@takezoe 
> If you don't have it

If it works with the "Free Trial" than I'll update it.

**Comment by aadrian** [comment]
@takezoe I updated the screenshots to new ones with the same size.

**Comment by takezoe** [comment]
@aadrian Thanks! I will be update the laptop image at a later date.

**Pull request merged**
