### PR TITLE
New article: Why doesn’t GitBucket self-hosting?

### PR DESCRIPTION
**Pull request by takezoe**

### CODE REVIEW

**Comment by McFoggy** [comment]
+1 for the article but really people are crazy with all this github/microsoft bashing

**Comment by aadrian** [comment]
@takezoe @McFoggy I changed the wording a little bit. I hope it's OK.

**Comment by takezoe** [comment]
@aadrian Thanks for your review :-) I changed a filename according to your updates because it's exposed as URL. I'll publish this article soon.

**Comment by takezoe** [comment]
@McFoggy I agree with you. Many people are talking about the acquisition of GitHub by Microsoft now, but it will quiet down quickly. In fact, I guess most of popular open source projects on GitHub will not move away from GitHub if Microsoft will not take a wrong strategy for their communities.

**Pull request merged**
